Repository hmcts/wa-message-cron-service, pull requests merged in 2023-01, with the labels that each got.

#106 RWA-2123 - Update Dependencies
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-106

#100 RWA-2081 add new message job for setting message state
  src/main/model/job-names.ts
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-100

#116 RWA-2190: Fix package vulnerability on nightly build
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-116

#117 RWA-2187 - afterSuccess Jenkinsfile_CNP and Jenkinsfile_nightly
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-117
