Repository hmcts/wa-message-cron-service, pull requests merged in 2023-10, with the labels that each got.

#263 downgrade Chalk
  .github/renovate.json
  package.json
  src/main/modules/appinsights/index.ts
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-263

#274 RWA-2864 Downgrade node
  .github/renovate.json
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-274

#282 RWA-2873 new CVE Suppression and downgrade eslint-plugin-prettier ver…
  .github/renovate.json
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-282

#283 RWA-2873 new CVE Suppression updated yarn-audit-known-issues file
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-283

#292 RWA-2873 Upgrade traverse library
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-292

#288 RWA-2882: Excluding helmet from auto upgrading by renovate
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-288
