Repository hmcts/wa-message-cron-service, pull requests merged in 2024-04, with the labels that each got.

#514 RWA-2447: Upgrade Webpack and Delete Dependbot
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-514

#526 RWA-3278: Upgrade tar
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-526

#535 RWA-3301: Update formidable
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-535

#544 RWA-3315: Downgrade helmet and chalk
  package.json
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-544
