Repository hmcts/wa-message-cron-service, pull requests merged in 2024-09, with the labels that each got.

#634 RWA-3736: Upgrade job to 2.1.2
  charts/wa-message-cron-service/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-634

#637 RWA-3784: Add to known issues file
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-637

#643 RWA-3818: Suppress path-to-regexp
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-643

#649 RWA-3839: Suppress CVEs
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-649
