Repository hmcts/wa-message-cron-service, pull requests merged in 2024-08, with the labels that each got.

#610 RWA-3670: Reconfigure renovate PRs
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-610

#613 RWA-3701: Ignore CVE-2024-39338
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-613

#615 RWA-3708: Upgrade Axios
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-615

#620 RWA-3743: Add to known issues
  yarn-audit-known-issues
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-620

#627 RWA-3751: Upgrade micromatch and update suppressions
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-message-cron-service-pr-627
